### ISSUE TITLE
X/TwitterやYoutubeの埋め込み

### ISSUE THREAD

**Issue by takipone** [cm-devcamp/app-an-dev#3]
- コーポレートサイトをSNSと連動させるべく、公式アカウントの埋め込みを追加します。
    - X/Twitter公式アカウント: クラスメソッド（@classmethod）さん / X https://x.com/classmethod
    - Youtube公式アカウント: クラスメソッド - YouTube https://www.youtube.com/@classmethod-yt

**Comment by takipone** [comment]
口頭でお伝えした通り、いずれもツイートや動画が埋め込まれるWebコンポーネントの埋め込みをお願いします。

**Comment by ryurin4567** [comment]
PR 作成後にすみません。
youtube の埋め込みはどの部分を埋め込めばよいでしょうか？

今回は youtube の チャンネルの ホーム画面の動画としましたが、
想定と違った場合ご連絡お願いします。

**Comment by takipone** [comment]
Youtubeチャンネルの代表的な動画が出てくればと思いましたが、特定の動画の固定表示になりそうでしょうか。

**Comment by ryurin4567** [comment]
はい、代表的な動画などは  トークン 発行が必要なYoutube API を利用する必要があります。https://developers.google.com/youtube/v3?hl=ja

そのため特定の動画の固定表示としました。

**Comment by takipone** [comment]
かしこまりました、ではその形でお願いします。
