### ISSUE TITLE
Google Analyticsの設置

### ISSUE THREAD

**Issue by takipone** [cm-devcamp/app-an-dev#5]
コーポレートサイトのアクセス解析を取り入れることになりました。つきましては、以下の説明に従いGoogle Analyticsのタグを埋め込んでください。

```
Google タグの設定方法を選択
手動でインストールする おすすめ
以下は、このアカウントの Google タグです。このタグをコピーして、ウェブサイトのすべてのページのコード（<head> 要素の直後）に貼り付けます。各ページに複数の Google タグを実装することはできません。
```

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXX');
</script>
```

**Comment by Keiichi-Tokumichi** [comment]
@takipone 
いくつか、確認をさせてください。
１：G-XXXXXXXX とありますが、これはこのまま埋め込んでよいのでしょうか？それとも個別のコードなどの指定がありますでしょうか？
２：このコードを埋め込むことで、具体的にどのような結果になればよいでしょうか？
　　テストの際に想定する挙動について確認したいです（Googleの検索タグなので、ブラウザ上に表示などはされない、と認識しています）

**Comment by takipone** [comment]
@Keiichi-Tokumichi 
はい、以下でお願いします。
1. `G-XQB3FPP59C`を利用ください
2. こちらで動作確認を行いますので、開発者ツールでスクリプト実行に関するエラーが発生しないことを確認ください。

**Comment by Keiichi-Tokumichi** [comment]
@takipone 
ありがとうございます。
> 1.G-XQB3FPP59Cを利用ください
承知しました。

>こちらで動作確認を行いますので、開発者ツールでスクリプト実行に関するエラーが発生しないこと
こちらも承知しました。

コードを埋め込みましたら、プルリクエストさせていただきます。

**Comment by takipone** [comment]
よろしくお願いします！

**Comment by Keiichi-Tokumichi** [comment]
Google タグを埋め込み、LiveServerでChromeで確認しました。

画面の表示に崩れなどのエラーは発生していません。
Chromeではいくつかエラーが出ていました。
![image](https://github.com/cm-devcamp/app-an-dev/assets/80370857/33cabe4c-8b8f-4e78-8766-70be6a59c006)

>Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
→　調査した結果、Chromeの拡張機能によるエラーのようで、環境個別なので蒸しでよいでしょうか？
　　参考サイト：https://goat-inc.co.jp/blog/3482/

>cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
Tailwind CSSのプラグインアラームのようです。テスト環境固有のため、こちらも無視でよろしいでしょうか？

>Third-party cookie will be blocked. Learn more in the Issues tab.
こちらもアラームレベルで、ChromeでのサードパーティCookieの段階的廃止による警告のようです。
今回のIssue要件とは直接関係がないと思われますので、無視でよろしいでしょうか？
https://sbapp.net/appnews/app/google/thirdpartycookiewillbeblocked-156629

**Comment by takipone** [comment]
はい、それぞれ無視で大丈夫そうです。Google Analyticsのコンソールを確認してみます。

**Comment by takipone** [comment]
Google Analyticsのコンソールで確認できました。

![Notification_Center](https://github.com/cm-devcamp/app-an-dev/assets/1150500/962d6921-0d39-4da3-9e77-ba87ab8febfe)

**Comment by Keiichi-Tokumichi** [comment]
同様にLiveServerでEdgeで確認しました。

画面の表示に崩れなどのエラーは発生していません。
Edgeでもいくつかエラーが出ていました。
![image](https://github.com/cm-devcamp/app-an-dev/assets/80370857/690be3e3-9b70-41f5-8f04-765e976a3a7a)

>?plugins=forms:61  cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation

→　Chromeと同じtailwind.cssのプラグインアラートです。同様に無視の対応とさせていただきます。

>Failed to load resource: the server responded with a status of 404 (Not Found)

→　なぜか favicon.ico というソースコードに無いファイルが見つからない、というエラーです。
　　ブラウズエリアの表示にエラーはないので、Edge固有のエラーなのかもしれません。
　　こちらも無視とさせていただきます。
